apiVersion: v1
kind: ConfigMap
metadata:
  name: configmapcommon

data:
  ASPNETCORE_URLS: "http://+:8080"
  RabbitMQ__OrderQueueName: "order-placed"
  RabbitMQ__PaymentProcessQueueName: "catalog-payment-processed"